### ISSUE TITLE
vivox7 上加载docview，会抛出异常

### ISSUE THREAD

**Issue by dawsonjiang** [CCVideo/Live_Android_Play_SDK#3]
vivox7 上加载docview，会抛出异常

-
![1584430491](https://user-images.githubusercontent.com/17867071/76832739-e8349580-6864-11ea-9e50-0f3378992abe.png)

**Comment by dawsonjiang** [comment]
![1584430491](https://user-images.githubusercontent.com/17867071/76832796-08645480-6865-11ea-9251-0fd459477480.png)

**Comment by dawsonjiang** [comment]
android.view.InflateException: Binary XML file line #37: Error inflating class com.bokecc.sdk.mobile.live.widget.DocView

**Comment by ddssingsong** [comment]
已经修复
